name: Docker Image Build and Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERTOKEN }}" | docker login -u "YashSharma1402" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t yash140204/fastapi-app:latest .
          docker push yash140204/fastapi-app:latest